"""
Shaft component module for 0D steady-state engine simulation.
Calculates the net mechanical power balance for spool equilibrium.
"""

from dataclasses import dataclass


@dataclass
class ShaftOutput:
    power_net: float  # Net power imbalance (must be 0 at steady-state) [W]


class Shaft:
    """
    Mechanical Shaft component.
    Evaluates the balance between turbine power generation and compressor/fan consumption,
    accounting for mechanical transmission efficiency and accessory power extraction.
    """

    def __init__(self, eta_mech: float = 0.99, power_ext: float = 0.0):
        self.eta_mech = eta_mech  # Mechanical transmission efficiency [-]
        self.power_ext = (
            power_ext  # Accessory power extraction (e.g., electrical generators) [W]
        )

    def calculate(self, power_in: float, power_out: float) -> ShaftOutput:
        """
        Executes the mechanical power balance.

        Args:
            power_in: Sum of mechanical power generated by all driving turbines [W]
            power_out: Sum of mechanical power consumed by all driven compressors/fans [W]
        """
        # Steady-state equilibrium requires power_net = 0.0
        # Net Power = (Turbine Power * Mechanical Efficiency) - Compressor Power - Accessory Power
        power_net = (power_in * self.eta_mech) - power_out - self.power_ext

        return ShaftOutput(power_net=power_net)
